"""Import collection snapshots exported by `run_export_collection`."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from discogs_player.core.settings import set_setting
from discogs_player.data.db import LATEST_SCHEMA_VERSION, get_connection
from discogs_player.data.repo import (
    get_release_counts,
    upsert_market_price,
    upsert_releases,
    upsert_spotify_mapping,
)

VALID_CONFLICT_MODES = {"merge", "replace"}


def _normalize_conflict_mode(raw: str) -> str:
    mode = raw.strip().lower()
    if mode not in VALID_CONFLICT_MODES:
        raise ValueError("Conflict mode must be 'merge' or 'replace'.")
    return mode


def _to_int(value: Any, *, field: str) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        text = value.strip()
        if text.isdigit():
            return int(text)
    raise ValueError(f"Invalid integer for '{field}': {value!r}")


def _to_optional_int(value: Any, *, field: str) -> int | None:
    if value is None:
        return None
    try:
        parsed = _to_int(value, field=field)
    except ValueError:
        return None
    return parsed


def _to_optional_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return float(text)
        except ValueError:
            return None
    return None


def _to_optional_str(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _to_bool(value: Any, *, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return value != 0
    if isinstance(value, str):
        text = value.strip().lower()
        if text in {"1", "true", "yes", "y", "on"}:
            return True
        if text in {"0", "false", "no", "n", "off"}:
            return False
    return default


def _to_str_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    values: list[str] = []
    for item in value:
        text = _to_optional_str(item)
        if text:
            values.append(text)
    return values


def _normalize_release(raw: Any, *, idx: int) -> dict[str, object]:
    if not isinstance(raw, dict):
        raise ValueError(f"Invalid release at index {idx}: expected object.")

    release_id = _to_int(raw.get("discogs_release_id"), field="discogs_release_id")
    if release_id <= 0:
        raise ValueError(f"Invalid release id at index {idx}: must be > 0.")

    year = _to_optional_int(raw.get("year"), field=f"releases[{idx}].year")
    if year is not None and year <= 0:
        year = None

    return {
        "discogs_release_id": release_id,
        "artist": _to_optional_str(raw.get("artist")),
        "title": _to_optional_str(raw.get("title")),
        "year": year,
        "genres": _to_str_list(raw.get("genres")),
        "styles": _to_str_list(raw.get("styles")),
        "thumb_url": _to_optional_str(raw.get("thumb_url")),
        "cover_url": _to_optional_str(raw.get("cover_url")),
        "added_at": _to_optional_str(raw.get("added_at")),
        "last_synced_at": _to_optional_str(raw.get("last_synced_at")),
        "is_active": 1 if _to_bool(raw.get("is_active"), default=True) else 0,
    }


def _normalize_settings(raw: Any) -> dict[str, str]:
    if raw is None:
        return {}
    if not isinstance(raw, dict):
        raise ValueError("Invalid 'settings' payload: expected object.")

    settings: dict[str, str] = {}
    for key, value in raw.items():
        normalized_key = str(key).strip()
        if not normalized_key:
            continue
        if value is None:
            continue
        settings[normalized_key] = str(value)
    return settings


def _normalize_schema_version(value: Any) -> int:
    try:
        schema_version = _to_int(value, field="schema_version")
    except ValueError as exc:
        raise ValueError(
            "Invalid or missing 'schema_version' in import payload."
        ) from exc
    if schema_version < 1:
        raise ValueError("Unsupported schema version in import payload.")
    if schema_version > LATEST_SCHEMA_VERSION:
        raise ValueError(
            "Import payload was generated by a newer schema version. "
            "Upgrade discogs_player before importing this snapshot."
        )
    return schema_version


def _load_import_payload(path: Path) -> dict[str, object]:
    if not path.exists():
        raise ValueError(f"Input path does not exist: {path}")
    if path.is_dir():
        raise ValueError(f"Input path is a directory: {path}")

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Import file is not valid JSON: {exc}") from exc
    except OSError:
        raise

    if not isinstance(payload, dict):
        raise ValueError("Import payload must be a JSON object.")
    return payload


def run_import_collection(
    *,
    input_path: str,
    conflict_mode: str = "merge",
    dry_run: bool = False,
    include_settings: bool = True,
) -> dict[str, object]:
    mode = _normalize_conflict_mode(conflict_mode)
    path = Path(input_path).expanduser()
    payload = _load_import_payload(path)
    schema_version = _normalize_schema_version(payload.get("schema_version"))

    raw_releases = payload.get("releases")
    if not isinstance(raw_releases, list):
        raise ValueError("Import payload must include a 'releases' list.")

    payload_release_count = payload.get("release_count")
    if payload_release_count is not None:
        expected_count = _to_int(payload_release_count, field="release_count")
        if expected_count != len(raw_releases):
            raise ValueError(
                "Import payload validation failed: release_count does not match number of releases."
            )

    releases: list[dict[str, object]] = []
    mappings: list[dict[str, object]] = []
    market_prices: list[dict[str, object]] = []
    for idx, item in enumerate(raw_releases):
        release = _normalize_release(item, idx=idx)
        releases.append(release)

        if isinstance(item, dict):
            spotify_album_id = _to_optional_str(item.get("spotify_album_id"))
            if spotify_album_id:
                mappings.append(
                    {
                        "discogs_release_id": _to_int(
                            release.get("discogs_release_id"),
                            field=f"releases[{idx}].discogs_release_id",
                        ),
                        "spotify_album_id": spotify_album_id,
                        "confidence": _to_optional_float(
                            item.get("spotify_confidence")
                        ),
                        "last_checked_at": _to_optional_str(
                            item.get("spotify_last_checked_at")
                        ),
                        "is_override": _to_bool(
                            item.get("spotify_is_override"), default=False
                        ),
                    }
                )

            has_market_payload = any(
                item.get(key) not in (None, "")
                for key in (
                    "market_lowest",
                    "market_median",
                    "market_highest",
                    "market_currency",
                    "market_last_updated_at",
                )
            )
            if has_market_payload:
                market_prices.append(
                    {
                        "discogs_release_id": _to_int(
                            release.get("discogs_release_id"),
                            field=f"releases[{idx}].discogs_release_id",
                        ),
                        "lowest": _to_optional_float(item.get("market_lowest")),
                        "median": _to_optional_float(item.get("market_median")),
                        "highest": _to_optional_float(item.get("market_highest")),
                        "currency": _to_optional_str(item.get("market_currency")),
                        "last_updated_at": _to_optional_str(
                            item.get("market_last_updated_at")
                        ),
                    }
                )

    settings = _normalize_settings(payload.get("settings")) if include_settings else {}

    conn = get_connection()
    try:
        pre_counts = get_release_counts(conn)
        pre_settings_count = int(
            conn.execute("SELECT COUNT(*) FROM app_settings").fetchone()[0]
        )

        if not dry_run:
            if mode == "replace":
                conn.execute("DELETE FROM market_prices")
                conn.execute("DELETE FROM spotify_mapping")
                conn.execute("DELETE FROM releases")
                if include_settings:
                    conn.execute("DELETE FROM app_settings")
                conn.commit()

            imported_release_count = upsert_releases(conn, releases)
            imported_mapping_count = 0
            for mapping in mappings:
                mapping_discogs_release_id = _to_int(
                    mapping.get("discogs_release_id"),
                    field="mappings[].discogs_release_id",
                )
                mapping_spotify_album_id = _to_optional_str(mapping.get("spotify_album_id"))
                if not mapping_spotify_album_id:
                    continue
                mapping_confidence = _to_optional_float(mapping.get("confidence"))
                mapping_last_checked_at = _to_optional_str(mapping.get("last_checked_at"))
                mapping_is_override = _to_bool(mapping.get("is_override"), default=False)
                upsert_spotify_mapping(
                    conn,
                    discogs_release_id=mapping_discogs_release_id,
                    spotify_album_id=mapping_spotify_album_id,
                    confidence=mapping_confidence,
                    last_checked_at=mapping_last_checked_at,
                    is_override=mapping_is_override,
                )
                imported_mapping_count += 1

            imported_market_price_count = 0
            for market_price in market_prices:
                market_discogs_release_id = _to_int(
                    market_price.get("discogs_release_id"),
                    field="market_prices[].discogs_release_id",
                )
                market_lowest = _to_optional_float(market_price.get("lowest"))
                market_median = _to_optional_float(market_price.get("median"))
                market_highest = _to_optional_float(market_price.get("highest"))
                market_currency = _to_optional_str(market_price.get("currency"))
                market_last_updated_at = _to_optional_str(
                    market_price.get("last_updated_at")
                )
                upsert_market_price(
                    conn,
                    discogs_release_id=market_discogs_release_id,
                    lowest=market_lowest,
                    median=market_median,
                    highest=market_highest,
                    currency=market_currency,
                    last_updated_at=market_last_updated_at,
                )
                imported_market_price_count += 1

            imported_settings_count = 0
            if include_settings:
                for key, value in settings.items():
                    set_setting(key, value, conn=conn)
                    imported_settings_count += 1
        else:
            imported_release_count = len(releases)
            imported_mapping_count = len(mappings)
            imported_market_price_count = len(market_prices)
            imported_settings_count = len(settings)
    finally:
        conn.close()

    return {
        "ok": True,
        "input_path": str(path),
        "dry_run": dry_run,
        "conflict_mode": mode,
        "include_settings": include_settings,
        "snapshot_schema_version": schema_version,
        "payload_release_count": len(raw_releases),
        "imported_release_count": imported_release_count,
        "imported_mapping_count": imported_mapping_count,
        "imported_market_price_count": imported_market_price_count,
        "imported_settings_count": imported_settings_count,
        "pre_import_release_count_total": int(pre_counts["release_count_total"]),
        "pre_import_release_count_active": int(pre_counts["release_count_active"]),
        "pre_import_mapped_count": int(pre_counts["mapped_count"]),
        "pre_import_settings_count": pre_settings_count,
    }
